<?php

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

// curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/x-www-form-urlencoded','Accept: application/json'));
curl_setopt($ch, CURLOPT_URL, 'https://developers.zomato.com/api/v2.1/categories');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'User-Key: c24c14b4dc580ef848ee99034dd0dbb1';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);

$result = json_decode($result);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

echo "<pre>"; print_r($result);





$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://developers.zomato.com/api/v2.1/cities?city_ids=280');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result_cities = curl_exec($ch);
$result_cities = json_decode($result_cities);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);
print_r($result_cities);





$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://developers.zomato.com/api/v2.1/collections?city_id=280');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result_collections = curl_exec($ch);
$result_collections = json_decode($result_collections);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);
print_r($result_collections);



$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://developers.zomato.com/api/v2.1/restaurant?res_id=16774318');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'User-Key: c24c14b4dc580ef848ee99034dd0dbb1';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result_restaurant = curl_exec($ch);
$result_restaurant = json_decode($result_restaurant);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);
print_r($result_restaurant);

?>